---
title: "IPMH PPW RCT Survey Weekly Report"
author: "David Owaga & Yuwei Wang"
date: "`r Sys.Date()`"
output:
  word_document
---

```{r setup, echo = F, include = F}
rm(list = ls())

pacman::p_load(knitr, tidyverse, ggplot2, psych, janitor, dplyr, 
               openxlsx, gtsummary, kableExtra, ggrepel, UpSetR, funModeling, gt, mice) 

knitr::opts_chunk$set(fig.width = 10, fig.height = 12)

ppw_rct_df <- read.csv("C:/Users/DAMARIS/Desktop/IPMH/RCT/PPW RCT Survey/IPMHAim23Questionnai_DATA_2025-03-04_2036.csv")

screening_consent_df <- read.csv("C:/Users/DAMARIS/Desktop/IPMH/RCT/PPW RCT Survey/IPMHRCTScreeningEnro_DATA_2025-03-04_2032.csv")

pm_survey_df <- read.csv("C:/Users/DAMARIS/Desktop/IPMH/PM+/IPMHProblemManagemen_DATA_2025-02-27_0917.csv")

daily_closeout_df <- read.csv("C:/Users/DAMARIS/Desktop/IPMH/RCT/Daily Close Out/IPMHFacilityDailyClo_DATA_2025-03-04_1236.csv")

ppw_rct_df <- ppw_rct_df %>%
    filter(!is.na(clt_ptid)) %>% 
    mutate(arm = ifelse(clt_study_site %in% 
                         c(1, 3, 4, 7, 9, 13, 16, 17, 19, 22), 
                     "Intervention", "Control"))


```



```{r check ID, message=FALSE, warning=FALSE, include=FALSE}
# check the IDs in the consenting database

consent_df <- screening_consent_df %>% 
    filter(ipmh_rct_enrollment_consent_complete == 2)

consent_id <-consent_df %>% 
    select(partipant_id) %>% 
    distinct()

#check the IDs in the survey database
survey_id <- ppw_rct_df %>% 
    select(clt_ptid) %>% 
    distinct()

#compare -------------------------------------------------------------------
### Those that are in the RCT, but not in the Consent database
setdiff(consent_id$partipant_id, survey_id$clt_ptid)
### Those that are in the consent, while missing in RCT database
setdiff(survey_id$clt_ptid, consent_id$partipant_id) 

```


```{r Reasons for ineligibility or not enrolled, echo=FALSE, message=FALSE, warning=FALSE}
ineligible <- screening_consent_df %>% 
    select(record_id, rct_harm_thought,  rct_memory_problem, 
            rct_aud_hallucinations,
             rct_vis_hallucinations, rct_paranoia, rct_delusions,
             rct_eligible_age, calc_gestation, rct_eligible_gestation,
             rct_eligible_phq2,  rct_eligible_gad2,  rct_eligible_harm, 
            rct_eligible, rct_enrolling, rct_decline_reason,  
            rct_other_reasons) %>% 
    filter(rct_eligible == 0 |rct_enrolling == 0) %>% 
    mutate(reasons = case_when(
        calc_gestation < 28 ~ "Gestation <28 Weeks",
        rct_eligible == 0 & rct_enrolling == 0 ~ NA_character_,
        rct_delusions == 1 ~ "Holds unusual beliefs",
        rct_memory_problem == 1 ~ "Difficulty with memory",
        rct_harm_thought == 1 ~ "Thought of Self Harm",
         rct_paranoia == 1 ~ "Paranoia",
        rct_eligible_gestation == 0 ~ "Gestation <28 Weeks",
        TRUE ~ NA_character_  # Assign NA if none of the conditions match
  ))

ineligible_df <- 
    ineligible %>% 
    filter(rct_eligible == 0)

ineligible_df %>% 
    tbl_summary(
        include = c(reasons),
        label = list(reasons = "Reasons for Ineligibility"),
        sort = list(all_categorical() ~ "frequency")# Sort categorical levels by frequency in descending order
        ) %>% 
    bold_labels() %>%
    as_gt() %>%
  # modify with gt functions
    gt::tab_header("Table 1: Summary of Ineligible Participants and Reasons") %>%
    gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))

not_enrolled <- ineligible %>% 
    filter(rct_eligible == 1 & rct_enrolling == 0) %>%
    mutate(rct_decline_reason = recode(rct_decline_reason,
                                       "1"= "Not interested",
                                       "2"= "Not enough time",
                                       "3"= "Consult spouse",
                                       "4"= "Concerns about confidentiality",
                                       "5" ="Time to think about it",
                                       "6" ="Other (specify) ___"))

not_enrolled %>%
    filter(rct_enrolling == 0) %>% 
    tbl_summary(include = c(rct_decline_reason),
                sort = list(all_categorical() ~ "frequency"),# Sort categorical levels by frequency in descending order
                label = list(rct_decline_reason ~ "Reasons for declining Enrollment")) %>% 
    bold_labels() %>%
    as_gt() %>%
  # modify with gt functions
  gt::tab_header("Table 2: Summary Reasons for Declining Enrollment") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))
```


## Consort


```{r Summary of Study Enrollment by Facility, echo=FALSE, message=FALSE, warning=FALSE}
Enrollments <- screening_consent_df %>%
    group_by(study_site) %>%
    reframe(Screened = n(),
            `Eligible` = sum(rct_eligible == 1),
            `Enrolled` = sum(rct_enrolling == 1, na.rm = "TRUE"),
            `% Enrolled (of Eligible)` = round((Enrolled / Eligible) * 100)) %>%
    rename(`Facility` = study_site) %>%
    mutate(Facility = recode(Facility,
                             "01" = "Rwambwa SCH",
                               "02" = "Sigomere SCH",
                               "03" = "Uyawi SCH",
                               "04" = "Got Agulu SCH",
                               "05" = "Ukwala SCH",
                               "06" = "Madiany SCH",
                               "07" = "Kabondo SCH",
                               "08" = "Mbita SCH",
                               "09" = "Miriu HC",
                               "11" = "Nyandiwa Level 4",
                               "13" = "Ober Kamoth SCH",
                               "14" = "Gita SCH",
                               "15" = "Akala HC",
                               "16" = "Usigu HC",
                               "17" = "Ramula HC",
                               "18" = "Simenya HC",
                               "19" = "Airport HC (Kisumu)",
                               "20" = "Nyalenda HC",
                               "21" = "Mirogi HC",
                               "22" = "Ndiru Level 4")) %>%
    bind_rows(summarise(.,Facility = "Overall",
                        Screened = sum(Screened),
                        Eligible = sum(Eligible),Enrolled = sum(Enrolled),
                        `% Enrolled (of Eligible)` = ifelse(sum(Eligible) > 0, round((sum(Enrolled) / sum(Eligible)) * 100, 1), NA)))  %>%
    arrange(desc(`Enrolled`))%>%
    gt() %>%
    tab_header(title = "Table 1: Summary of Study Enrollment by Facility",subtitle = "Showing Participants enrollments") %>%
    tab_style(style = cell_text(weight = "bold"),locations = cells_body(rows = Facility == "Overall")) %>%
    tab_options(table.font.size = px(12))

Enrollments
```



## Enrollment Per Facility

```{r Enrolment Per Facility, echo=FALSE, message=FALSE, warning=FALSE}
enrolled <- screening_consent_df %>% 
        filter(rct_enrolling == 1) %>% 
    select(study_site, rct_enrolling) %>% 
    group_by(study_site) %>% 
    reframe(Actual = sum(rct_enrolling)) %>% 
    mutate(study_site = recode(study_site,
                               "01" = "Rwambwa SCH",
                               "02" = "Sigomere SCH",
                               "03" = "Uyawi SCH",
                               "04" = "Got Agulu SCH",
                               "05" = "Ukwala SCH",
                               "06" = "Madiany SCH",
                               "07" = "Kabondo SCH",
                               "08" = "Mbita SCH",
                               "09" = "Miriu HC",
                               "11" = "Nyandiwa Level 4",
                               "13" = "Ober Kamoth SCH",
                               "14" = "Gita SCH",
                               "15" = "Akala HC",
                               "16" = "Usigu HC",
                               "17" = "Ramula HC",
                               "18" = "Simenya HC",
                               "19" = "Airport HC (Kisumu)",
                               "20" = "Nyalenda HC",
                               "21" = "Mirogi HC",
                               "22" = "Ndiru Level 4")) %>% 
    rename(Facility = study_site)

# Set a constant target value based on the period
target_value <- 10

# Use mutate with the pipe operator to add the target column
enrolled <- enrolled %>%
  mutate(target = target_value)

# Reorder Facility factor based on descending Actual values
enrolled <- enrolled %>%
  mutate(Facility = factor(Facility, levels = Facility[order(-Actual)]))

# Calculate total Actual
total_actual <- sum(enrolled$Actual, na.rm = TRUE)



ggplot(enrolled, aes(x = Facility, y = Actual, fill = Facility)) +
  geom_bar(stat = "identity") +  # Bar plot for actual values, filled by Facility
  geom_hline(yintercept = target_value, linetype = "dashed", color = "magenta", size = 1) +  # Target line
  geom_text(aes(label = Actual), vjust = -0.5) +  # Add labels on bars
  annotate("text", x = 3, y = target_value + 0.2, label = as.character(target_value), color = "black") +  # Label for target
  labs(
    title = paste("Enrollment Per Facility (n =", total_actual, ")"),
    y = "",
    x = ""
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(face = "bold", hjust = 0.5),
    legend.position = "none"   # Remove the legend
  )

```

## PPW Demographics

Altogether, we currently have data for `r nrow(ppw_rct_df)` participants.

```{r Basic Demographic Summary, echo=F, message=FALSE, warning=FALSE}
demographics_df <- ppw_rct_df %>% 
  select(clt_date, arm, starts_with("dem_"), demographics_complete)%>% 
     mutate(dem_age = if_else(
         dem_dob_uk == 1,
         floor(time_length(interval(dem_dob, clt_date), "years")),
    dem_age
  ))


demographics_df <- demographics_df %>% 
    mutate(dem_current_partner = dplyr::recode(dem_current_partner, 
                               "1" = "Yes",
                               "0" = "No",
                               "-2" = "Don't know/No Answer")) %>% 
  mutate(dem_maritalstat = dplyr::recode(dem_maritalstat, 
                                       "1" = "Currently married",
                                       "2" = "Divorced/separated",
                                       "3" = "Come we stay", 
                                       "4" = "Steady boyfriend", 
                                       "5" = "Never married",
                                       "6" = "Widow",
                                       "7" = "Single",
                                       "8" = "Prefer not to answer"
                                       ),
         dem_marriage = recode(dem_marriage,
                               "1" = "Monogamous",
                               "2" = "Polygamous",
                               "77" = "Prefer not to answer"),
         dem_currentpartner_father = recode(dem_currentpartner_father,
                                            "1"= "Yes",
                                            "0" = "No",
                                            "2" = "Unsure",
                                            "-2" = "No Answer"),
         dem_partner_financial = recode(dem_partner_financial,
                                        "1" = "Yes",
                                        "0" = "No",
                                        "-2" = "No Answer"),
         dem_pc_residence = recode(dem_pc_residence,
                                   "1" = "Yes",
                                   "0" = "No",
                                   "77" = "Prefer not to answer"),
         dem_employment = recode(dem_employment,
                                 "1" ="Yes",
                                 "0" = "No",
                                 "77" = "Prefer not to answer"),
         dem_pc_residence = recode(dem_pc_residence,
                                   "1" = "Yes",
                                   "0" = "No",
                                   "77" = "Prefer not to answer"))



# basic demo table
demographics_df %>% tbl_summary(
    
    #by = "arm",
    sort = list(all_categorical() ~ "frequency"),  # Sort categorical levels by frequency in descending order
    include=c(dem_age, dem_current_partner, dem_maritalstat,
    dem_marriage, dem_currentpartner_father, dem_partner_financial, 
    dem_pc_residence, dem_current_school, dem_school, dem_employment,
    dem_household_num, dem_housesleep, dem_houserooms, dem_traveltime_min),
    label = list(dem_age ~ "Age (Years)",
                 dem_current_partner ~ "Do you currently have a partner (Yes)",
                 dem_partner_financial ~ "Does your partner provide financial support to you?",
                 dem_employment ~ "Do you have regular employment? (Yes)",
                 dem_maritalstat ~ "Marital status",
                 dem_currentpartner_father ~ "Is your current partner the father of this baby",
                 dem_pc_residence ~ "Shares residence with partner",
                 dem_marriage ~ "Type of marriage",
                 dem_current_school ~ "Currently in School",
                 dem_school ~ "Completed years in School",
                 dem_household_num ~ "Number of people in Household",
                 dem_housesleep ~ "Number of people sleep in same house",
                 dem_houserooms ~ "Rooms in the house most often sleep in",
                 dem_traveltime_min ~ "Time to the Clinic (Minutes"),
    missing = "no",
    digits = list(all_continuous() ~ 1), 
    type = list(dem_age ~ "continuous", 
              dem_household_num ~ "continuous",
              dem_housesleep ~ "continuous", 
              dem_houserooms ~ "continuous", 
              dem_traveltime_min ~ "continuous"),
  statistic = list(all_continuous() ~ "{median} [IQR: {p25}, {p75}]")) %>% 
  bold_labels() %>%
    add_n() %>% 
    #add_p() %>% 
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("Table 1: Basic Demographic Summary") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(14))
```

## PM+ and Telepsychiatry Referrals
```{r PM+ and Telepsychiatry Referrals, echo=FALSE, message=FALSE, warning=FALSE}
pm_telep_df <- ppw_rct_df %>% 
    filter(redcap_event_name == "enrollment_arm_1") %>% 
    select(record_id, clt_study_site, clt_date, starts_with("abs_")) %>% 
    mutate(phq9_scores = rowSums(select(., abs_phq_interest, abs_phq_down,
                                        abs_phq_sleep, abs_phq_tired, 
                                        abs_phq_appetite, abs_phq_bad,
                                        abs_phq_concentrate, abs_phq_slow, 
                                        abs_phq_dead), na.rm = TRUE),
        gad7_scores = rowSums(select(., abs_gad7_nerve, abs_gad7_uncontrol,
                                        abs_gad7_worry, abs_gad7_relax, 
                                        abs_gad7_restless, abs_gad7_annoyed,
                                        abs_gad7_afraid), na.rm = TRUE))%>% 
    filter(phq9_scores >= 10|gad7_scores >= 10) %>% 
    mutate(clt_study_site = recode(clt_study_site,
                               "01" = "Rwambwa SCH",
                               "03" = "Uyawi SCH",
                               "04" = "Got Agulu SCH",
                               "07" = "Kabondo SCH",
                               "09" = "Miriu HC",
                               "13" = "Ober Kamoth SCH",
                               "16" = "Usigu HC",
                               "17" = "Ramula HC",
                               "19" = "Airport HC (Kisumu)",
                               "22" = "Ndiru Level 4")) %>% 
    mutate(referred_to = case_when(
    (phq9_scores >= 10 & phq9_scores < 15 & abs_phq_ref_pm == 1) |
    (gad7_scores > 9 & gad7_scores < 15 & abs_gad7_ref_pm == 1) ~ "PM+",
    
    (phq9_scores >= 15 & abs_phq_ref_tele == 1) |
    (gad7_scores >= 15 & abs_gad7_ref_tele == 1) ~ "Telepsychiatry",
    TRUE ~ NA_character_  # Assigns NA if none of the conditions are met
  ))

pm_sessions <- 
    pm_survey_df %>% 
    group_by(pm_ptid) %>% 
    reframe(sessions_attended = n()-1) # Take away Pre-intervention PSYCHLOPS measurement

pm_telep_df <- pm_telep_df %>% 
    left_join(pm_sessions, by = c("record_id" = "pm_ptid"))
    


pm_telep_df %>% 
    tbl_summary(by = "referred_to",
                sort = list(all_categorical() ~ "frequency"),  # Sort categorical levels by frequency in descending order
        include = c(clt_study_site, sessions_attended),
        label = list(clt_study_site ~ "Facility",
                     sessions_attended ~ "PM+ Sessions Attended")
    ) %>% 
    bold_labels() %>% 
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header(
      title = "Table 3: PM+ and Telepsychiatry referrals",
      subtitle = "Showing Participants Referred to PM+ or Telepsychiatry") %>%
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(14))

```


```{r PM+ and Telepsychiatry Referral QCs, message=FALSE, warning=FALSE, include=FALSE}
referral_qc <- pm_telep_df %>% 
    filter(phq9_scores > 9 & abs_phq_ref_pm == 0 | gad7_scores > 9 & 
               abs_gad7_ref_pm == 0) %>% 
    select(record_id, clt_study_site, clt_date, phq9_scores, abs_phq_ref_pm,
           gad7_scores, abs_gad7_ref_pm)

```


```{r echo=FALSE, message=FALSE, warning=FALSE}
pm_follow_up <- pm_survey_df %>% 
    select(pm_ptid, pm_facility, pm_date) %>%
    right_join(pm_telep_df %>% 
                  select(record_id, clt_date), by = c("pm_ptid" = "record_id")) %>% 
    select(pm_ptid, clt_date, pm_date, )

# Function to generate weekly visit status
generate_weekly_visits <- function(pm_follow_up) {
    pm_follow_up %>%
        mutate(clt_date = as.Date(clt_date),  # Ensure clt_date is Date
               pm_date = as.Date(pm_date)) %>%  # Ensure pm_date is Date
        group_by(pm_ptid) %>%
        summarise(clt_date = first(clt_date), 
                  pm_dates = list(na.omit(pm_date)), 
                  .groups = "drop") %>%
        rowwise() %>%
        mutate(
            week_1 = as.integer(any(pm_dates > clt_date & pm_dates <= clt_date + 7)),
            week_2 = as.integer(any(pm_dates > clt_date + 7 & pm_dates <= clt_date + 14)),
            week_3 = as.integer(any(pm_dates > clt_date + 14 & pm_dates <= clt_date + 21)),
            week_4 = as.integer(any(pm_dates > clt_date + 21 & pm_dates <= clt_date + 28)),
            week_5 = as.integer(any(pm_dates > clt_date + 28 & pm_dates <= clt_date + 35)),
            week_6 = as.integer(any(pm_dates > clt_date + 35 & pm_dates <= clt_date + 42))
        ) %>%
        select(pm_ptid, clt_date, week_1, week_2, week_3, week_4, week_5, week_6)
}
# Apply function
weekly_visits <- generate_weekly_visits(pm_follow_up)

# View result
weekly_visits %>% 
    gt() %>%
  tab_header(
    title = "Summary of PM+ Enrollments",
    subtitle = "Showing Participants Enrolled in PM+ and Follow-up"
  ) %>%
  tab_options(
    table.font.size = px(12)
  )

```

