---
title: "IPMH RCT IS Survey - HCW - Baseline"
author: "David Owaga & Yuwei Wang"
date: "`r Sys.Date()`"
output:
  word_document
---

```{r setup, echo = F, include = F, warning=F}
rm(list = ls())

pacman::p_load(knitr, tidyverse, ggplot2, psych, janitor, dplyr, 
               openxlsx, gtsummary, kableExtra, ggrepel, UpSetR, funModeling, gt, mice) 

knitr::opts_chunk$set(fig.width = 10, fig.height = 12)

#Read data by exporting data from REDCap
#is_survey_df <- read.csv("C:/Users/DAMARIS/Desktop/IPMH/RCT/IS HCWs Survey/IPMHAim23RCTISSurvey_DATA_2025-02-07_0605.csv")

#Read data using datapull
source("REDCap_datapull.R")
is_survey_df <- rct_hcw

#consenting database for cross-check 
rct_hcw_consenting_baseline <- rct_hcw_consenting %>%
    filter(is.na(redcap_repeat_instrument)) %>% 
    filter(redcap_event_name == "Pre-launch assessment (Arm 1: arm)")
```

## Health Care Workers Demographics

Altogether, we currently have data for `r nrow(is_survey_df)` participants.

```{r check ID, echo=F, message=FALSE, warning=FALSE, include= F}
#check the IDs in the consenting database
consent_id <-rct_hcw_consenting_baseline %>% 
    select(screen_id) %>% 
    distinct()

#check the IDs in the survey database
survey_id <- is_survey_df %>% 
    select(pt_id) %>% 
    distinct()

#compare
setdiff(consent_id$screen_id, survey_id$pt_id) #2 IDs in the consenting database are not in the survey database
setdiff(survey_id$pt_id, consent_id$screen_id) #2 IDs in the survey database are not in the consenting database


rct_hcw %>% count(pt_id) %>% filter(n > 1)
#23010026 has two record in the survey database

#compare the whole row for this ID
rct_hcw %>% filter(pt_id == "23010026")
```

```{r Basic Demographic Summary, echo=F, message=FALSE, warning=FALSE}
is_survey_df <- is_survey_df %>%
    mutate(
        facility_num = str_extract(facility_id, "^[0-9]+"),  # Extracts only the leading number
        arm = case_when(
            facility_num %in% c("01", "03", "04", "07", "09", "13", "16", "17", "19", "22") ~ "Intervention",
            TRUE ~ "Control"
        ))

demogra <- is_survey_df %>% 
  select(arm, part_id,  pt_type, facility_id, calculated_pt_id, 
         dob_uk, age, cal_age, sex, education, 
         dpt___1, dpt___2, dpt___3, dpt___4, dpt___5, dpt___6, dpt___7, 
          job_arm14___1,  job_arm14___2,  job_arm25___1,  job_arm25___2, 
         job_arm25___3, job_arm25___4,  job_arm25___5,  job_arm25___6, 
         job_arm25___7, job_arm36___1,  job_arm36___2,  job_arm36___3,  
         job_arm7___1, job_arm7___2,
          monthsjob, monthswork, terms, care,  wlwh, monthscare,
          hrscare, wlwh,  demographic_complete)%>% 
    filter(demographic_complete == "Complete") %>% 
    mutate(age_final = case_when(
        dob_uk == "Yes" ~ floor(as.numeric(cal_age)),
        dob_uk == "No" ~ as.numeric(age),
        TRUE ~ NA_real_))

demogra <- demogra %>% 
  #   mutate(sex = dplyr::recode(sex, 
  #                              "1" = "Male",
  #                              "2" = "Female")) %>% 
  # mutate(education = dplyr::recode(education, 
  #                                      "1" = "No schooling completed",
  #                                      "2" = "Primary school",
  #                                      "3" = "Secondary school", 
  #                                      "4" = "Diploma", 
  #                                      "5" = "Bachelor's degree or higher degree"),
  #        education = fct_relevel(education,
  #                                "Diploma", "Bachelor's degree or higher degree",
  #                                "Secondary school", "Primary school")) %>%
  mutate(designation = dplyr::case_when(
      job_arm14___1 == "Checked" ~ "HTS counsellor",
      job_arm14___2 == "Checked" ~ "Mentor Mother",
      job_arm25___1 == "Checked" ~ "Medical officer",
      job_arm25___2 == "Checked" ~ "Obstetrician/gynaecologist",
      job_arm25___3 == "Checked" ~ "Clinical Officer",
      job_arm25___4 == "Checked" ~ "Nurses",
      job_arm25___6 == "Checked" ~  "Other social worker",
      job_arm25___7 == "Checked" ~ "Others",
      job_arm36___1 == "Checked" ~ "Medical officer",
      job_arm36___2 == "Checked" ~ "Clinical Officer",
      job_arm36___3 == "Checked" ~ "Nurses",
      job_arm7___1 == "Checked" ~ "Psychologist",
      job_arm7___2 == "Checked" ~ "Psychiatrist",
      TRUE ~ NA_character_)) %>%
  # mutate(care = dplyr::recode(care, 
  #                               "0" = "No",
  #                               "1" = "Yes"),
  #          wlwh = dplyr::recode(wlwh,
  #                               "0" = "No",
  #                               "1" = "Yes")) %>% 
  #   mutate(terms = dplyr::recode(terms, 
  #                                "1" = "Permanent and pensionable", 
  #                                "2" = "Contract",
  #                                "3" = "Volunteer", 
  #                                "4" = "Other"),
  #          terms = fct_relevel(terms,
  #                                "Contract", "Permanent and pensionable", 
  #                                "Volunteer", "Other")) %>% 
  mutate(monthsjob = as.numeric(monthsjob, monthswork,  monthscare, hrscare)#,
         # pt_type = recode(pt_type,
         #                  "22" = "Lay providers",
         #                  "23" = "Facility-in-charge",
         #                  "24" = "Nurses/COs/MOs",
         #                  "25" = "Psychiatrists/Psychologists")
         )%>% 
  mutate(yearjob = monthsjob/12) %>% 
    mutate(yearwork = monthswork/12) %>% 
    mutate(yearcare = monthscare/12)

# basic demo table
demogra %>% tbl_summary(
    by = "arm",
    include=c(arm, age_final, sex, education, dpt___1, dpt___2, 
            dpt___3, dpt___4, dpt___5, dpt___6, dpt___7,
            designation,  yearjob, yearwork, yearcare, 
            hrscare, terms, care,  wlwh),
    label = list(age_final ~ "Age (Years)",
               sex ~ "Gender",
               education ~ "Education level",
               dpt___1 ~ "Working in antenatal care",
               dpt___2 ~ "Working in postnatal care",
               dpt___3 ~ "Working in immunization clinic",
               dpt___4 ~ "Working in PMTCT",
               dpt___5 ~ "Working in family planning clinic",
               dpt___6 ~ " Psychological/Psychiatric care",
               dpt___7 ~ "Working in other department",
               designation ~ "Current Designation",
               yearjob ~ "Current job duration (Years)",
               yearwork ~ "Duration in the facility (Years)",
               terms ~ "Terms of engagement in the facility",
               care ~ "Offering care to perinatal women (Yes)",
               yearcare ~ "Duration of offering care to PW in the facility (Years)",
               hrscare ~ "Hours/week taking care of PW in the facility", 
               wlwh ~ "Currently providing care to PW living with HIV (Yes)"),
    missing = "no",
    digits = list(all_continuous() ~ 1), 
    type = list(age_final ~ "continuous", 
              yearjob ~ "continuous",
              yearwork ~ "continuous", 
              yearcare ~ "continuous", 
              hrscare ~ "continuous"),
  statistic = list(all_continuous() ~ "{median} [IQR: {p25}, {p75}]")) %>% 
    add_overall() %>% 
    add_p() %>% 
  bold_labels() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("Basic Demographic Summary") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))
```

```{r Participants Interviewed by cadre per facility, echo=FALSE, message=FALSE, warning=FALSE}
suveys_done <- is_survey_df %>% 
    select(pt_id, facility_id, pt_type) %>% 
    # mutate(pt_type = recode(pt_type,
    #                         "22" = "Lay providers",
    #                         "23" = "Facility-in-charge",
    #                         "24" = "Nurses/COs/medical officers",
    #                         "25" = "Psychiatrists/psychologists"),
    #        facility_id = dplyr::recode(facility_id, 
    #                                "01" = "Rwambwa Sub-county Hospital",
    #                                "02" = "Sigomere Sub County Hospital",
    #                                "03" = "Uyawi Sub County Hospital",
    #                                "04" = "Got Agulu Sub-District Hospital",
    #                                "05" = "Ukwala Sub County Hospital",
    #                                "06" = "Madiany Sub County Hospital",
    #                                "07" = "Kabondo Sub County Hospital",
    #                                "08" = "Mbita Sub-County Hospital",
    #                                "09" = "Miriu Health Centre",
    #                                "11" = "Nyandiwa Level IV Hospital",
    #                                "13" = "Ober Kamoth Sub County Hospital",
    #                                "14" = "Gita Sub County Hospital",
    #                                "15" = "Akala Health Centre",
    #                                "16" = "Usigu Health Centre",
    #                                "17" = "Ramula Health Centre",
    #                                "18" = "Simenya Health Centre",
    #                                "19" = "Airport Health Centre (Kisumu)",
    #                                "20" = "Nyalenda Health Centre",
    #                                "21" = "Mirogi Health Centre",
    #                                "22" = "Ndiru Level 4 Hospital")) %>%
    group_by(facility_id, pt_type) %>%
  summarise(count = n(), .groups = "drop")%>%
  pivot_wider(names_from = pt_type, values_from = count, values_fill = 0)%>%
  mutate(`Total_Facility` = rowSums(across(where(is.numeric)))) %>%  # Add row totals
  arrange(desc(Total_Facility)) %>%  # Arrange in descending order
    bind_rows(summarise(., across(where(is.numeric), sum), facility_id = "Total"))%>%  # Add column totals
    gt() %>%
  tab_header(
    title = "Summary of HCWs Surveyed by Facility",
    subtitle = "Showing counts of each HCWs type per facility"
  ) %>%
  cols_label(
    facility_id = "Facility",
    Total_Facility = "Total"
  ) %>%
  tab_options(
    table.font.size = px(12)
  )
suveys_done
```


## Organizational readiness - HCW

```{r echo=FALSE, message=FALSE, warning=FALSE}
hcw_readiness_df <- is_survey_df %>% 
    select(pt_id, facility_id, pt_type, arm, oric_needed_1, oric_needed_2,
    oric_motivated_1, oric_motivated_2, oric_motivated_3, oric_motivated_4, 
    oric_expectancy_1, oric_expectancy_2, oric_demand_1, oric_demand_2, 
    oric_demand_3, oric_demand_4, oric_resource_1, oric_resource_2, 
    oric_context_1, oric_context_2, oric_capacity_1, oric_capacity_2, 
    oric_capacity_3, oric_flex_1, oric_flex_2, oric_flex_3, oric_flex_4, 
    oric_politic, organizational_readiness_hcw_complete) %>% 
    filter(!pt_type == "Facility-in-charge: 23")

hcw_readiness_df <- hcw_readiness_df %>%
    filter(!is.na(pt_type)) %>%  # Remove rows where pt_type is NA
    mutate(pt_type = droplevels(factor(pt_type))) %>% 
    filter(!is.na(facility_id)) %>% 
    mutate(facility_id = droplevels(factor(facility_id))) 

hcw_readiness_df <- hcw_readiness_df %>% 
    mutate(across(starts_with("oric_"), ~ case_when(
        . == "1: Completely disagree" ~ 1,
        . == "2: Disagree" ~ 2,
        . == "3: Neither agree nor disagree" ~ 3,
        . == "4: Agree" ~ 4,
        . == "5: Completely agree" ~ 5,
        . == "Prefer not to answer" ~ NA_real_,  # Convert to NA
        TRUE ~ as.numeric(as.character(.))  # Ensure numeric conversion
    ))) %>%  
    mutate(
        oric_change_commitment = rowMeans(select(., c(starts_with("oric_motivated"), 
                                                      starts_with("oric_needed"), 
                                                      starts_with("oric_expectancy"))), 
                                          na.rm = TRUE),
        oric_change_efficacy = rowMeans(select(., c(starts_with("oric_demand"), 
                                                    starts_with("oric_resource"), 
                                                    starts_with("oric_context"))), 
                                        na.rm = TRUE),
        oric_capacity = rowMeans(select(., starts_with("oric_capacity")), na.rm = TRUE),
        oric_flex = rowMeans(select(., starts_with("oric_flex")), na.rm = TRUE),
        oric_org = as.numeric(rowMeans(select(., starts_with("oric_politic")), na.rm = TRUE))
    )
```

```{r, continuous, echo=FALSE, message=FALSE, warning=FALSE}
#show the mean score of each domain by arm using tbl_summary
hcw_readiness_df %>% 
    tbl_summary(
        by = arm,
        include = c(oric_change_commitment, oric_change_efficacy, oric_capacity, oric_flex, oric_org),
        type = list(oric_org ~ "continuous"),
        label = list(oric_change_commitment ~ "Change commitment",
                     oric_change_efficacy ~ "Change efficacy",
                     oric_capacity ~ "Capacity",
                     oric_flex ~ "Flexibility",
                     oric_org ~ "Organizational structure"),
        missing = "no",
        statistic = list(all_continuous() ~ "{median} [IQR: {p25}, {p75}]")) %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("HCWs Organizational Readiness Summary by Arm") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))

# by pt_type
hcw_readiness_df %>% 
    tbl_summary(
        by = pt_type,
        include = c(oric_change_commitment, oric_change_efficacy, oric_capacity, oric_flex, oric_org),
        type = list(oric_org ~ "continuous"),
        label = list(oric_change_commitment ~ "Change commitment",
                     oric_change_efficacy ~ "Change efficacy",
                     oric_capacity ~ "Capacity",
                     oric_flex ~ "Flexibility",
                     oric_org ~ "Organizational structure"),
        statistic = list(all_continuous() ~ "{median} [IQR: {p25}, {p75}]"),
        missing = "no") %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("HCWs Organizational Readiness By Participant Type") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))

#by facility
hcw_readiness_df %>% 
    tbl_summary(
        by = facility_id,
        include = c(oric_change_commitment, oric_change_efficacy, oric_capacity, oric_flex, oric_org),
        type = list(oric_org ~ "continuous"),
        label = list(oric_change_commitment ~ "Change commitment",
                     oric_change_efficacy ~ "Change efficacy",
                     oric_capacity ~ "Capacity",
                     oric_flex ~ "Flexibility",
                     oric_org ~ "Organizational structure"),
        statistic = list(all_continuous() ~ "{median} [IQR: {p25}, {p75}]"),
        missing = "no") %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("HCWs Organizational Readiness By Facility") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))
```

```{r, binary, echo=FALSE, message=FALSE, warning=FALSE}
#making the scores binary
hcw_readiness_df <- hcw_readiness_df %>% 
    mutate(across(c(oric_change_commitment, oric_change_efficacy, oric_capacity, oric_flex, oric_org),
                  ~case_when(. >= 4 ~ "High",
                             . < 4 ~ "Low",
                             TRUE ~ as.character(.))),
           across(c(oric_change_commitment, oric_change_efficacy, oric_capacity, oric_flex, oric_org), as.factor))  # Convert to factor

# Show the proportion of high and low scores by arm
hcw_readiness_df %>% 
    tbl_summary(
        by = arm,
        include = c(oric_change_commitment, oric_change_efficacy, oric_capacity, oric_flex, oric_org),
        type = list(oric_change_commitment ~ "categorical",
                    oric_change_efficacy ~ "categorical",
                    oric_capacity ~ "categorical",
                    oric_flex ~ "categorical",
                    oric_org ~ "categorical"),
        label = list(oric_change_commitment ~ "Change commitment",
                     oric_change_efficacy ~ "Change efficacy",
                     oric_capacity ~ "Capacity",
                     oric_flex ~ "Flexibility",
                     oric_org ~ "Organizational structure"),
        missing = "no") %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
    # Convert from gtsummary object to gt object
    as_gt() %>%
    # Modify with gt functions
    gt::tab_header("HCWs Organizational Readiness Summary") %>% 
    gt::tab_options(
        table.font.size = "medium",
        data_row.padding = gt::px(1)) %>%
    tab_options(table.font.size = px(12))

# by pt_type
hcw_readiness_df %>% 
    tbl_summary(
        by = pt_type,
        include = c(oric_change_commitment, oric_change_efficacy, oric_capacity, oric_flex, oric_org),
        type = list(oric_org ~ "categorical"),  
        label = list(oric_change_commitment ~ "Change commitment",
                     oric_change_efficacy ~ "Change efficacy",
                     oric_capacity ~ "Capacity",
                     oric_flex ~ "Flexibility",
                     oric_org ~ "Organizational structure"),
        missing = "no") %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
    as_gt() %>%
    gt::tab_header("HCWs Organizational Readiness By Participant Type") %>% 
    gt::tab_options(
        table.font.size = "medium",
        data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))

#by facility
hcw_readiness_df %>% 
    tbl_summary(
        by = facility_id,
        include = c(oric_change_commitment, oric_change_efficacy, oric_capacity, oric_flex, oric_org),
        type = list(oric_org ~ "categorical"),
        label = list(oric_change_commitment ~ "Change commitment",
                     oric_change_efficacy ~ "Change efficacy",
                     oric_capacity ~ "Capacity",
                     oric_flex ~ "Flexibility",
                     oric_org ~ "Organizational structure"),
        missing = "no") %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
    as_gt() %>%
    gt::tab_header("HCWs Organizational Readiness By Facility") %>% 
    gt::tab_options(
        table.font.size = "medium",
        data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))
```


```{r in-charge, echo=FALSE, message=FALSE, warning=FALSE}
incharge_readiness_df <- is_survey_df %>% 
    select(pt_id,pt_type, facility_id, arm,
            oric_needed_1_fic, oric_needed_2_fic, oric_motivated_1_fic,
           oric_motivated_2_fic,
           oric_motivated_3_fic, oric_motivated_4_fic, leadership_fic,
           politic_fic, oric_expectancy_1_fic, oric_expectancy_2_fic, 
           oric_demand_2_fic, oric_demand_3_fic, oric_demand_4_fic, oric_demand_4_fic,
           oric_resource_3_fic, oric_resource_1_fic, oric_resource_4_fic,  
           oric_resource_2_fic,oric_context_1_fic, oric_context_2_fic, 
           oric_capacity_1_fic, oric_capacity_2_fic, oric_capacity_3_fic, 
           oric_flex_1_fic, oric_flex_2_fic, oric_flex_3_fic,
           organizational_readiness_facilityincharge_complete) %>% 
    filter(pt_type == "Facility-in-charge: 23") 

incharge_readiness_df <- incharge_readiness_df %>% 
    filter(!is.na(pt_type)) %>%  # Remove rows where pt_type is NA
    mutate(pt_type = droplevels(factor(pt_type))) %>% 
    filter(!is.na(facility_id)) %>% 
    mutate(facility_id = droplevels(factor(facility_id))) 

incharge_readiness_df <- incharge_readiness_df %>% 
    mutate(across(ends_with("_fic"), ~ case_when(
        str_detect(., "Completely disagree") ~ 1,  
        str_detect(., "Disagree") ~ 2,  
        str_detect(., "Neither agree nor disagree") ~ 3,  
        str_detect(., "Agree") ~ 4, 
        str_detect(., "Completely agree") ~ 5, 
        str_detect(., "Prefer not to answer") ~ NA_real_,  # Convert to NA
        TRUE ~ as.numeric(as.character(.))  # Ensure numeric conversion
    )))%>%  
    mutate(
        oric_change_commitment = rowMeans(select(., c(starts_with("oric_motivated"), 
                                                      starts_with("oric_needed"),
                                                      starts_with("oric_expectancy"))), 
                                          na.rm = TRUE),
        oric_change_efficacy = rowMeans(select(., c(starts_with("oric_demand"), 
                                                    starts_with("oric_resource"), 
                                                    starts_with("oric_context"))), 
                                        na.rm = TRUE),
        oric_capacity = rowMeans(select(., starts_with("oric_capacity")), na.rm = TRUE),
        oric_flex = rowMeans(select(., starts_with("oric_flex")), na.rm = TRUE),
        oric_org = (rowMeans(select(., c(starts_with("leadership"), 
                                    starts_with("politic"))), na.rm = TRUE))
    )
```

```{r, continuous, echo=FALSE, message=FALSE, warning=FALSE}
#show the mean score of each domain by arm using tbl_summary
incharge_readiness_df %>% 
    tbl_summary(
        by = arm,
        include = c(oric_change_commitment, oric_change_efficacy, oric_capacity, oric_flex, oric_org),
        type = list(oric_org ~ "continuous",
                    oric_change_commitment ~ "continuous",
                    oric_change_efficacy ~ "continuous",
                    oric_capacity ~ "continuous",
                    oric_flex ~ "continuous"),
        label = list(oric_change_commitment ~ "Change commitment",
                     oric_change_efficacy ~ "Change efficacy",
                     oric_capacity ~ "Capacity",
                     oric_flex ~ "Flexibility",
                     oric_org ~ "Organizational structure"),
        missing = "no",
        statistic = list(all_continuous() ~ "{median} [IQR: {p25}, {p75}]")) %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("Facility In-charge Organizational Readiness Summary by Arm") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))

# by facility
incharge_readiness_df %>% 
    tbl_summary(
        by = facility_id,
        include = c(oric_change_commitment, oric_change_efficacy, oric_capacity, oric_flex, oric_org),
        type = list(oric_org ~ "continuous",
                    oric_change_commitment ~ "continuous",
                    oric_change_efficacy ~ "continuous",
                    oric_capacity ~ "continuous",
                    oric_flex ~ "continuous"),
        label = list(oric_change_commitment ~ "Change commitment",
                     oric_change_efficacy ~ "Change efficacy",
                     oric_capacity ~ "Capacity",
                     oric_flex ~ "Flexibility",
                     oric_org ~ "Organizational structure"),
        missing = "no",
        statistic = list(all_continuous() ~ "{median} [IQR: {p25}, {p75}]")) %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("Facility In-charge Organizational Readiness By Facility") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))
```

```{r, binary, echo=FALSE, message=FALSE, warning=FALSE}
#making the scores binary
incharge_readiness_df <- incharge_readiness_df %>% 
    mutate(across(c(oric_change_commitment, oric_change_efficacy, oric_capacity, oric_flex, oric_org),
                  ~case_when(. >= 4 ~ "High",
                             . < 4 ~ "Low",
                             TRUE ~ as.character(.))),
           across(c(oric_change_commitment, oric_change_efficacy, oric_capacity, oric_flex, oric_org), as.factor))  # Convert to factor

# Show the proportion of high and low scores by arm
incharge_readiness_df %>% 
    tbl_summary(
        by = arm,
        include = c(oric_change_commitment, oric_change_efficacy, oric_capacity, oric_flex, oric_org),
        type = list(oric_change_commitment ~ "categorical",
                    oric_change_efficacy ~ "categorical",
                    oric_capacity ~ "categorical",
                    oric_flex ~ "categorical",
                    oric_org ~ "categorical"),
        label = list(oric_change_commitment ~ "Change commitment",
                     oric_change_efficacy ~ "Change efficacy",
                     oric_capacity ~ "Capacity",
                     oric_flex ~ "Flexibility",
                     oric_org ~ "Organizational structure"),
        missing = "no") %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
    # Convert from gtsummary object to gt object
    as_gt() %>%
    # Modify with gt functions
    gt::tab_header("Facility In-charge Organizational Readiness Summary") %>% 
    gt::tab_options(
        table.font.size = "medium",
        data_row.padding = gt::px(1)) %>%
    tab_options(table.font.size = px(12))

# by facility
incharge_readiness_df %>% 
    tbl_summary(
        by = facility_id,
        include = c(oric_change_commitment, oric_change_efficacy, oric_capacity, oric_flex, oric_org),
        type = list(oric_org ~ "categorical",
                    oric_change_commitment ~ "categorical",
                    oric_change_efficacy ~ "categorical",
                    oric_capacity ~ "categorical",
                    oric_flex ~ "categorical"),
        label = list(oric_change_commitment ~ "Change commitment",
                     oric_change_efficacy ~ "Change efficacy",
                     oric_capacity ~ "Capacity",
                     oric_flex ~ "Flexibility",
                     oric_org ~ "Organizational structure"),
        missing = "no") %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
    # Convert from gtsummary object to gt object
    as_gt() %>%
    # Modify with gt functions
    gt::tab_header("Facility In-charge Organizational Readiness By Facility") %>% 
    gt::tab_options(
        table.font.size = "medium",
        data_row.padding = gt::px(1)) %>%
    tab_options(table.font.size = px(12))
```

## Implementation Intention

```{r echo=FALSE, message=FALSE, warning=FALSE}
intention_df <- is_survey_df %>% 
    select(pt_id,pt_type, facility_id, arm,
           intention_1, intention_2, intention_3,
           implementation_intention_complete) %>% 
    filter(!is.na(pt_type)) %>%  # Remove rows where pt_type is NA
    mutate(pt_type = droplevels(factor(pt_type))) %>% 
    filter(!is.na(facility_id)) %>% 
    mutate(facility_id = droplevels(factor(facility_id))) 
    

#by arm
intention_df %>% 
    tbl_summary(
        by = arm,
        include = c(intention_1, intention_2, intention_3),
        label = list(intention_1 ~ "I plan to use IPMH",
                     intention_2 ~ "Using IPMH is a high priority to me",
                     intention_3 ~ "I will use IPMH step relevant to my current role"),
        missing = "no") %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("Implementation Intention Summary by Arm") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))

#by pt_type
intention_df %>% 
    tbl_summary(
        by = pt_type,
        include = c(intention_1, intention_2, intention_3),
        label = list(intention_1 ~ "I plan to use IPMH",
                     intention_2 ~ "Using IPMH is a high priority to me",
                     intention_3 ~ "I will use IPMH step relevant to my current role"),
        missing = "no") %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("Implementation Intention Summary by Participant Type") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))

#by facility
intention_df %>% 
    tbl_summary(
        by = facility_id,
        include = c(intention_1, intention_2, intention_3),
        label = list(intention_1 ~ "I plan to use IPMH",
                     intention_2 ~ "Using IPMH is a high priority to me",
                     intention_3 ~ "I will use IPMH step relevant to my current role"),
        missing = "no") %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("Implementation Intention Summary by Facility") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
  tab_options(
        table.font.size = px(12))
```

## Acceptability, appropriateness, and feasibility

### IPMH Acceptability

```{r Acceptability, echo=FALSE, message=FALSE}
acceptability <- is_survey_df %>% 
    select(pt_id, pt_type, facility_id, arm, aim_1, aim_2,
           aim_3, aim_4) %>% 
    filter(arm == "Intervention") %>% 
    filter(!is.na(pt_type)) %>%  # Remove rows where pt_type is NA
    mutate(pt_type = droplevels(factor(pt_type))) %>% 
    filter(!is.na(facility_id)) %>% 
    mutate(facility_id = droplevels(factor(facility_id))) 
    
acceptability %>% 
    tbl_summary(
        by = "pt_type",
        include = c(aim_1, aim_2, aim_3, aim_4),
        label = list(aim_1 ~ "IPMH meets my approval", 
                     aim_2 ~ "IPMH is appealing to me", 
                     aim_3 ~ "I like IPMH.", 
                     aim_4 ~ "I welcome IPMH"),
        missing = "no") %>%     add_overall() %>% add_p() %>% 
    bold_labels() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("IPMH Acceptability") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))

#by facility
acceptability %>% 
    tbl_summary(
        by = facility_id,
        include = c(aim_1, aim_2, aim_3, aim_4),
        label = list(aim_1 ~ "IPMH meets my approval", 
                     aim_2 ~ "IPMH is appealing to me", 
                     aim_3 ~ "I like IPMH.", 
                     aim_4 ~ "I welcome IPMH"),
        missing = "no") %>%     add_overall() %>% add_p() %>%
    bold_labels() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("IPMH Acceptability by Facility") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
  tab_options(
        table.font.size = px(12))
```

### IPMH Appropriateness

```{r appropriateness, echo=FALSE, message=FALSE, warning=FALSE}
appropriateness <- is_survey_df %>% 
    select(part_id,pt_type, facility_id, arm, iam_1, iam_2, iam_3, iam_4) %>% 
    filter(arm == "Intervention") %>% 
    filter(!is.na(pt_type)) %>%  # Remove rows where pt_type is NA
    mutate(pt_type = droplevels(factor(pt_type))) %>% 
    filter(!is.na(facility_id)) %>% 
    mutate(facility_id = droplevels(factor(facility_id))) 

appropriateness %>% 
    tbl_summary(
        by = "pt_type",
        include = c(iam_1, iam_2, iam_3, iam_4),
        label = list(iam_1 ~ "IPMH seems fitting", 
                     iam_2 ~ "IPMH seems suitable", 
                     iam_3 ~ "IPMH seems applicable", 
                     iam_4 ~ "IPMH seems like a good match"),
        missing = "no") %>% add_overall() %>% add_p() %>%
    bold_labels() %>% 
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("IPMH Appropriateness") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))

#by facility
appropriateness %>% 
    tbl_summary(
        by = facility_id,
        include = c(iam_1, iam_2, iam_3, iam_4),
        label = list(iam_1 ~ "IPMH seems fitting", 
                     iam_2 ~ "IPMH seems suitable", 
                     iam_3 ~ "IPMH seems applicable", 
                     iam_4 ~ "IPMH seems like a good match"),
        missing = "no") %>% add_overall() %>% add_p() %>%
    bold_labels() %>% 
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("IPMH Appropriateness by Facility") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
  tab_options(
        table.font.size = px(12))
```

### IPMH Feasibility

```{r Feasibility, echo=FALSE, message=FALSE, warning=FALSE}
feasibility <- is_survey_df %>% 
    select(part_id,pt_type, facility_id, arm,  fim_1,  fim_2,  fim_3,  fim_4) %>% 
    filter(arm == "Intervention") %>% 
    filter(!is.na(pt_type)) %>%  # Remove rows where pt_type is NA
    mutate(pt_type = droplevels(factor(pt_type))) %>% 
    filter(!is.na(facility_id)) %>% 
    mutate(facility_id = droplevels(factor(facility_id))) 

feasibility %>% 
    tbl_summary(
        by = "pt_type",
        include = c( fim_1,  fim_2,  fim_3,  fim_4),
        label = list( fim_1 ~ "IPMH seems implementable", 
                      fim_2 ~ "IPMH seems possible", 
                      fim_3 ~ "IPMH seems doable", 
                      fim_4 ~ "IPMH seems easy to use"),
        missing = "no") %>% 
    bold_labels() %>% add_overall() %>% add_p() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("IPMH Feasibility") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))

#by facility
feasibility %>% 
    tbl_summary(
        by = facility_id,
        include = c( fim_1,  fim_2,  fim_3,  fim_4),
        label = list( fim_1 ~ "IPMH seems implementable", 
                      fim_2 ~ "IPMH seems possible", 
                      fim_3 ~ "IPMH seems doable", 
                      fim_4 ~ "IPMH seems easy to use"),
        missing = "no") %>% 
    bold_labels() %>% add_overall() %>% add_p() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("IPMH Feasibility by Facility") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
  tab_options(
        table.font.size = px(12))
```

## Stigma scale

```{r echo=FALSE, message=FALSE, warning=FALSE}
stigma_scale <- is_survey_df %>% 
    select(arm, part_id, pt_type, facility_id, 
           starts_with("social_distance_"), diagnostic,
           starts_with("disclose_"), starts_with("recovery_"), 
           starts_with("responsibility_"), danger) %>% 
    filter(!is.na(pt_type)) %>%  # Remove rows where pt_type is NA
    mutate(pt_type = droplevels(factor(pt_type))) %>%
    filter(!is.na(facility_id)) %>%
    mutate(facility_id = droplevels(factor(facility_id))) 
    
#Items 3, 8, 9, 10, 11, 15, 19 required reverse scoring.
#social_distance_2, recovery_1, recovery_2, disclose_5, responsibility_1, danger, social_distance_5

stigma_scale <- stigma_scale %>%
    mutate(across(c(starts_with("social_distance_"), starts_with("recovery_"), 
                    starts_with("disclose_"), starts_with("responsibility_"), danger),
                  ~ case_when(
                      str_detect(., "Completely disagree") ~ 1,
                      str_detect(., "Disagree") ~ 2,
                      str_detect(., "Neither agree nor disagree") ~ 3,
                      str_detect(., "Agree") ~ 4,
                      str_detect(., "Completely agree") ~ 5,
                      TRUE ~ as.numeric(as.character(.))
                  )),
           social_distance_2 = 6 - social_distance_2,
           recovery_1 = 6 - recovery_1,
           recovery_2 = 6 - recovery_2,
           disclose_5 = 6 - disclose_5,
           responsibility_1 = 6 - responsibility_1,
           danger = 6 - danger,
           social_distance_5 = 6 - social_distance_5) %>%
    mutate(
        social_distance = rowSums(select(., starts_with("social_distance_")), na.rm = TRUE),
        recovery = rowSums(select(., starts_with("recovery_")), na.rm = TRUE),
        disclose = rowSums(select(., starts_with("disclose_")), na.rm = TRUE),
        responsbility = rowSums(select(., starts_with("responsibility_")), na.rm = TRUE),
        danger = rowSums(select(., starts_with("danger")), na.rm = TRUE),
        total = rowSums(select(., starts_with("social_distance_"), starts_with("recovery_"), 
                             starts_with("disclose_"), starts_with("responsibility_"), starts_with("danger")), na.rm = TRUE)
    )

#by arm (range of the scale: 20 - 100)
stigma_scale %>% 
    tbl_summary(
        by = arm,
        include = c(social_distance, recovery, disclose, responsbility, danger, total),
        type = list(social_distance ~ "continuous",
                    recovery ~ "continuous",
                    disclose ~ "continuous",
                    responsbility ~ "continuous",
                    danger ~ "continuous",
                    total ~ "continuous"),
        label = list(social_distance ~ "Social distance",
                     recovery ~ "Recovery",
                     disclose ~ "Disclosure",
                     responsbility ~ "Responsibility",
                     danger ~ "Danger",
                     total ~ "Total score"),
        missing = "no",
        statistic = list(all_continuous() ~ "{mean} [SD: {sd}]")) %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("Stigma Scale Summary by Arm") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))

#by pt_type
stigma_scale %>% 
    tbl_summary(
        by = pt_type,
        include = c(social_distance, recovery, disclose, responsbility, danger, total),
        type = list(social_distance ~ "continuous",
                    recovery ~ "continuous",
                    disclose ~ "continuous",
                    responsbility ~ "continuous",
                    danger ~ "continuous",
                    total ~ "continuous"),
        label = list(social_distance ~ "Social distance",
                     recovery ~ "Recovery",
                     disclose ~ "Disclosure",
                     responsbility ~ "Responsibility",
                     danger ~ "Danger",
                     total ~ "Total score"),
        missing = "no",
        statistic = list(all_continuous() ~ "{mean} [SD: {sd}]")) %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("Stigma Scale Summary by Participant Type") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
    tab_options(
        table.font.size = px(12))

#by facility
stigma_scale %>% 
    tbl_summary(
        by = facility_id,
        include = c(social_distance, recovery, disclose, responsbility, danger, total),
        type = list(social_distance ~ "continuous",
                    recovery ~ "continuous",
                    disclose ~ "continuous",
                    responsbility ~ "continuous",
                    danger ~ "continuous",
                    total ~ "continuous"),
        label = list(social_distance ~ "Social distance",
                     recovery ~ "Recovery",
                     disclose ~ "Disclosure",
                     responsbility ~ "Responsibility",
                     danger ~ "Danger",
                     total ~ "Total score"),
        missing = "no",
        statistic = list(all_continuous() ~ "{mean} [SD: {sd}]")) %>% 
    add_overall() %>% add_p() %>% 
    bold_labels() %>%
  # convert from gtsummary object to gt object
  as_gt() %>%
  # modify with gt functions
  gt::tab_header("Stigma Scale Summary by Facility") %>% 
  gt::tab_options(
    table.font.size = "medium",
    data_row.padding = gt::px(1)) %>%
  tab_options(
        table.font.size = px(12))
```

